version: '3'
services:
  customer-db:
    image: postgres
    container_name: customer-db
    environment:
      - POSTGRES_PASSWORD=customer
      - POSTGRES_USER=customer
      - POSTGRES_DB=customer
    ports:
      - 5432:5432
    networks:
      - customer-network
  
  product-database:
    image: mariadb
    container_name: product-database
    environment:
      - MYSQL_ROOT_PASSWORD=product
      - MYSQL_USER=product
      - MYSQL_PASSWORD=product
      - MYSQL_DATABASE=product
    ports:
      - 3306:3306
    networks:
      - customer-network        
networks:
  customer-network:
    driver: bridge